name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest

    - name: Create pem file
      run: |
        run: echo "${{ secrets.EC2_PEM_FILE }}" | base64 -d > my-key.pem
        chmod 400 my-key.pem

    - name: Deploy to EC2
      run: |
        ssh -o "StrictHostKeyChecking=no" -i my-key.pem ec2-user@3.104.152.3 << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:latest
          docker stop myapp || true
          docker rm myapp || true
          docker run -d -p 80:80 -e RDS_USERNAME=admin -e RDS_PASSWORD=Yue2086329803. --name myapp ${{ secrets.DOCKER_USERNAME }}/myapp:latest
        EOF
